@startuml eric

left to right direction
actor Joueur
actor Ordinateur
rectangle "Jeu Tic Tac Toe" as Jeu {
  Joueur --> (Cliquer sur une case)
  (Cliquer sur une case) --> (Vérifier la victoire)
  (Cliquer sur une case) --> (Vérifier l'égalité)
  (Cliquer sur une case) --> (Choisir la difficulté)
  (Vérifier la victoire) --> (Afficher le message de victoire)
  (Vérifier l'égalité) --> (Afficher le message d'égalité)
  (Afficher le message de victoire) --> (Afficher le score)
  (Afficher le message d'égalité) --> (Afficher le score)
  Ordinateur --> (Jouer)
  (Jouer) --> (Vérifier la victoire)
  (Jouer) --> (Vérifier l'égalité)
  (Jouer) --> (Choisir la difficulté)
  (Vérifier la victoire) --> (Afficher le message de victoire)
  (Vérifier l'égalité) --> (Afficher le message d'égalité)
  (Choisir la difficulté) --> (Appliquer la difficulté)
  (Appliquer la difficulté) --> (Afficher la difficulté)
}

@enduml
